### ISSUE TITLE
Switch to another monospace font?

### ISSUE THREAD

**Issue by ThierryO** [inbo/INBOmd#15]
Currently we use `Courier New` as monospace font. It's not very pretty and quite wide. I've tested a fex alternatives: `Inconsolata`, `Latin Modern Mono` and `Nimbus 15 Mono`. [monospace.pdf](https://github.com/inbo/INBOmd/files/524848/monospace.pdf) provides a small example using the four different fonts.

Should we stick with `Courier New` or select on of the others? I suggest that all members from @inbo/bmk and @inbo/open-data cast their vote by commenting on this issue.

**Comment by PaulQuataert** [comment]
For me, inconsolata is hard to read, the other two are OK. Good idea to change the font.

**Comment by peterdesmet** [comment]
From the 4 options, I have a slight preference for `Inconsolata`, but I also like [Droid Sans Mono](https://www.fontsquirrel.com/fonts/droid-sans-mono) and [Consolas](http://www.fontpalace.com/font-details/Consolas/) (default in Sublime). Is it possible to add those to the mix? :smile:

**Comment by ThierryO** [comment]
Sure. The fonts are added to [the new file](https://github.com/inbo/INBOmd/files/526465/monospace.pdf). The fonts are ordered based on the width of the characters from narrow to wide. All font sizes are equal. Note that in the dummy paragraph `index.Rmd` and the URL are in the mono spaced font while the main font is Calibri.

**Comment by florisvdh** [comment]
Beware that Consolas and Courier New have proprietary licenses. See this [list](https://en.wikipedia.org/wiki/Category:Open-source_typefaces) on Wikipedia for an overview of open-source fonts. Another one perhaps worth trying - not on that list but recommended by [Lucas Westermann](https://issuu.com/fullcirclemagazine/docs/fullcircle-issue112-en/14) - is [Hack](http://sourcefoundry.org/hack/).

**Comment by DimEvil** [comment]
![image](https://cloud.githubusercontent.com/assets/3965195/19348022/0db48188-914c-11e6-96ac-8e48a4ccb1b8.png)

**Comment by ThierryO** [comment]
That's not a mono spaced font @DimEvil. So not an option ;-)

**Comment by ThierryO** [comment]
@florisvdh Calibri is neither free but still required by the INBO corporate style

**Comment by florisvdh** [comment]
Unfortunately, yes... "Still required" is not forever ;-)

**Comment by ElsLommelen** [comment]
If I look at the numbers, Inconsolata and Consolas are difficult to read because of the zero, and I do not like the style of the numbers of Latin Modern Mono.  The font size of Droid Sans Mono looks rather large compared to Calibri, and Nimbus 15 Mono looks hardly different from Courier New...  Is it possible to add Droid Sans Mono in a smaller font size?

**Comment by florisvdh** [comment]
For now, I am using Inconsolata (as specified in the inconsolata branch), within our templates, and I like it. Code chunks and output look clean, are well readable and they fit well with the rest of the template. It is sans serif (which I prefer) and it is a bit narrower (efficient use of space).

Only one remark. Inconsolata fits 'so well' with Calibri in the text paragraphs (for inline code) that it is not always obvious that another font has been used for `inline code`. So, in conjuction with using Inconsolata, I would prefer to see inline code in a _grey font_ (not too light, not too dark). That would make it more distinctive. But I see no need to do that for normal code chunks and output.

**Comment by ThierryO** [comment]
I've updated [monospace.pdf](https://github.com/inbo/INBOmd/files/580535/monospace.pdf) again. The changes: 
- keep only the free fonts
- try several options for the inline code: grey letters, smaller letters, light grey background

My personal favourite combination is smaller size with a light grey background with Inconsolata or Droid Sans Mono font

**Comment by ElsLommelen** [comment]
I would prefer Droid Sans Mono with smaller size (80%) and dark grey foreground (70-80% ?)

**Comment by florisvdh** [comment]
I think smaller size only works well for Droid Sans Mono, and for that font 80% looks better than 100%. At 80% it is more efficient than Inconsolata at 100%, regarding width. I like the font as such, but I prefer zeroes with a slash or dot inside, to make the distinction between `plotO` (with letter 'O') and `plot0` (with zero) for example. In Droid Sans Mono that is hard. In fact, among the fonts in the pdf, only Inconsolata provides zeroes with a mark.

I would propose two further additions:

- add fonts that place a dot inside zeroes: _DejaVu Sans Mono_ and perhaps _Ubuntu Mono_ (actually my favourite for on-screen coding; I don't know how it would look in a report)
- dark grey foreground (I agree with Els on that)

**Comment by ivyjansen** [comment]
- Totally agree with Floris concerning the zeroes.
- My suggestion would be
    - Inconsolata
    - Inline code size 100% with dark grey foreground (75%)
    - Code + output size 80%

**Comment by florisvdh** [comment]
I guess that this issue can be closed.

**Comment by ThierryO** [comment]
fixed in #14
