### ISSUE TITLE
Desired fixes in inbo_rapport_2015 on the short term: footnotes

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#22]
As discussed, and after further investigation. See this [example report](https://drive.google.com/open?id=0B-DYcTNHFnIXR2h5YklRcnV3LUk).

Footnotes:

- need to stay at the bottom of the page (p. 2, 26, 65, 91, 114, ...). Sometimes they do, however: I guess this is for pages at the end of a chapter (p. 104)
- need more separation (above the horizontal line) from the body text (p. 14, 55, 56, ...).

**Comment by florisvdh** [comment]
'more separation': graphics department says '2 more white lines'

**Comment by ThierryO** [comment]
I've set the margin at 1 cm and moved them to the bottom.

**Comment by ThierryO** [comment]
fixed in PR #14
