### ISSUE TITLE
Desired fixes in inbo_rapport_2015 on the short term: remove empty page after part title pages

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#23]
As discussed, and after further investigation. See this [example report](https://drive.google.com/open?id=0B-DYcTNHFnIXR2h5YklRcnV3LUk).

Parts: their title pages should not be followed by an empty page. ('deel 1, deel 2, deel 3, bijlagen')

**Comment by ThierryO** [comment]
This is a two sided report. The title page of the part goes on the right side. Then an empty page (on the left side) so that the text starts again on the right side. I won't fix this for now.
