### ISSUE TITLE
Desired fixes in inbo_rapport_2015 on the short term: white space in section titles

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#24]
As discussed, and after further investigation. See this [example report](https://drive.google.com/open?id=0B-DYcTNHFnIXR2h5YklRcnV3LUk).

Sections and lower levels should conform to the Microsoft Word template, they say.

The required space between the text margin (where the section number begins) and the start of the section title is:

- sections ('header 1'): 7.5 mm
- subsections ('header 2'): 10 mm
- subsubsections ('header 3'): 12.5 mm

This means the whitespaces will slightly shorten.

**Comment by florisvdh** [comment]
Concerning white space _above_ titles, INBOmd already provides more whitespace than the Word version. And manual empty lines are not the right solution in Word to provide more whitespace. So the vertical aspect can be ignored (for now).

**Comment by ThierryO** [comment]
the style rather defines the maximum width of the title than the space between number and text. we decrease this width in the past to allow for multi-digit numbers. Hence the horizontal white space is larger

**Comment by florisvdh** [comment]
In short, the current state is well thought through. I'll close this issue.
