### ISSUE TITLE
Desired fixes in inbo_rapport_2015 on the short term: some URLs in bibliography run off the page

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#25]
As discussed, and after further investigation. See this [example report](https://drive.google.com/open?id=0B-DYcTNHFnIXR2h5YklRcnV3LUk).

URLs in bibliography sometimes runs off the page (p. 174, 175).

**Comment by ThierryO** [comment]
@florisvdh please add a minimal working example.

**Comment by florisvdh** [comment]
Issue successfully solved by afbb239.

Thanks a lot!
