### ISSUE TITLE
Unneccessary space between lines in lists of figures and tables

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#29]
In the report example of [INBOmd_examples](https://github.com/inbo/inbomd_examples) the list of figures and the list of tables add whitespace when figures or tables are from a different chapter. I think this should be avoided.

**Comment by ThierryO** [comment]
That whitespace is also present in the table of content. Let's see what the communications department's opinion is.

**Comment by ThierryO** [comment]
Can you check if this is still an issue with the latest version? If it is, please add add a [mcve](https://stackoverflow.com/help/mcve). If solved, please close the issue.

**Comment by florisvdh** [comment]
I'm afraid the issue is still there. A reproducible example is provided by <https://github.com/inbo/inbomd_examples/tree/master/source/inbo_rapport>. See page 10 of the [rendered version](https://inbomd-examples.netlify.com/inbo_rapport/inbo_rapport.pdf) (e.g. space between 'tabel 7.1' and 'tabel 12.3'; same for figures).

**Comment by ThierryO** [comment]
I'm closing this for now because I can't find a solution. The extra vertical space splits figures and tables from different chapters. There is a point in doing that.
