### ISSUE TITLE
Page numbers of the list of figures and tables

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#30]
In the report example of [INBOmd_examples](https://github.com/inbo/inbomd_examples) the list of figures and the list of tables get a normal page number, while rather the roman page numbers should continue on those pages.

**Comment by florisvdh** [comment]
Maybe it is possible to offer a choice between the one/two sided report with a YAML parameter? Even if the two-sided report has the 'roman number' bug.

**Comment by ThierryO** [comment]
Another problem with the two sided report is that the user need to add a `\cleardoublepage` before each `# (PART) {-}`. That is required to force the title of the part to the odd page.

Allowing to switch between a one sided and two sided report via YAML is doable.
