### ISSUE TITLE
inbo_rapport: landscape oriented pages have too wide section titles

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#32]
There is too much whitespace between section number and text of the title, on landscape A4 pages.

**Comment by ThierryO** [comment]
Can you check if this is still an issue with the latest version? If it is, please add add a [mcve](https://stackoverflow.com/help/mcve). If solved, please close the issue.

**Comment by ThierryO** [comment]
Closing now. Please reopen with a [mcve](https://stackoverflow.com/help/mcve) is the problem still occurs.
