### ISSUE TITLE
inbo_rapport: appendices are not named as such

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#33]
Appendix titles distinguish themselves as chapter titles 'A xxxxxx', 'B xxxxxx', 'C xxxxxx', occurring after the numbered chapter titles (1, 2, 3, ...). However, it is not clarified to the reader that these effectively are appendices (not in the body, not in the TOC). This would better be the case, both with the appendices themselves, and in the table of contents.

I see two possible alternatives:

- either add an unnumbered part title page 'Bijlagen', which also appears as an unnumbered part title in the TOC;
- or just name these chapter numbers as 'Bijlage A: xxxxxxx', 'Bijlage B: xxxxxxx', and so on.

**Comment by florisvdh** [comment]
My current workaround is as follows.

1. In markdown:
```
# (APPENDIX) Bijlagen {-}

# Title of appendix A {#app:Alabel}

body text

# Title of appendix B {#app:Blabel}

body text
```
2. Additional insertion in LaTeX in order to make this part title appear in the TOC (the star suppresses numbering):
```
\part*{Bijlagen}\label{part-bijlagen}
\addcontentsline{toc}{part}{Bijlagen}
```

**Comment by ThierryO** [comment]
This issue should go in inbo/inbomd_examples since it requires work on the source code of the document, not of the style.
