### ISSUE TITLE
Pdf inbo_rapport: space below subsection and subsubsection titles

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#45]
I'm not sure which is the right corporate style, but there is a clear difference with [this recent VMM report](http://www.vmm.be/bestanden/VMM-2017-LKT_TW.pdf), where less space is applied below subsection (x.y) and subsubsection (x.y.z) titles than in the current INBOmd template.

So perhaps INBOmd is right and there is no issue. But I think the VMM example is nicer to the eye ;-)

**Comment by ThierryO** [comment]
Can you check if #46 is better?

**Comment by florisvdh** [comment]
Yep, that seems OK! Thanks.
