### ISSUE TITLE
changing font-family of INBOtheme to Calibri in INBO rapport template

### ISSUE THREAD

**Issue by ToonHub** [inbo/INBOmd#55]
The INBO rapport template attempts to change the font-family of INBOtheme to Calibri. This does not work in a windows OS. 
Following code should be added to make it work: 

`library(extrafont)`
`font_import()` : this should only be run once and takes a while... 
 `loadfonts(device = "win", quiet = TRUE)` 

Should we add the code to the template?

**Comment by ThierryO** [comment]
We added it to the README in e3750fbfe1e4695aa112913500aa5dd69a7a90d8
