### ISSUE TITLE
inbo_xxx() functions: requested changes in support of pandoc-citeproc + CSL

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#63]
As discussed past week.

- [ ] implement pandoc option "`--metadata lang=nl`" or  "`--metadata lang=en`" depending on the requested INBOmd style.
  - Currently `INBOmd` only guesses style-based languages for `babel` in tex, but that's used after pandoc-citeproc has already rendered citations when it uses csl.
- [ ] in case the user still actively provides the `lang` metadata key (in YAML header or through `pandoc_args` argument), this user setting should have priority
- [ ] for PDF output, set `citation_package = "none"` by default in order to use csl.

**Comment by ThierryO** [comment]
fixed in #69
