### ISSUE TITLE
Branch 0.4.10: use pandoc_metadata_arg("lang", lang) or pandoc option "--metadata lang=xx"

### ISSUE THREAD

**Issue by florisvdh** [inbo/INBOmd#67]
See comment https://github.com/inbo/INBOmd/commit/6491953414c0b377b7f670fbaea4fe7c0461f5c8#r44152111

Relates to #63 .

**Comment by ThierryO** [comment]
See https://github.com/inbo/INBOmd/commit/6491953414c0b377b7f670fbaea4fe7c0461f5c8#r44661418
