### ISSUE TITLE
cover text to UTF-8

### ISSUE THREAD

**Issue by ThierryO** [inbo/INBOmd#80]
The cover.txt is malformatted on windows when using `latin1` characters like `ç`.
Covering to UTF-8 might fix the problem.

    ok <- Encoding(cover_text) %in% c("UTF-8", "unknown")
    cover_text[!ok] <- iconv(cover_text[!ok], from = head(Encoding(cover_text)[!ok], 1), to = "UTF-8")

https://github.com/inbo/INBOmd/blob/1ec1bd489781507a3841311731e32eb2b223ae92/R/cover_info.R#L43

**Comment by ElsLommelen** [comment]
Oups, after developing code to solve this problem, I noticed this cover.txt was only malformatted when opening it in my RStudio, not when opening it in Kladblok or Notepad++ (and the code doesn't solve the RStudio encoding problem...)  So I guess this issue can be closed.

**Comment by ThierryO** [comment]
Thanks for looking into this issue.
