### ISSUE TITLE
simplify website inbo

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/INBOmd#81]
In the colofon of the Word template, [www.inbo.be](https://www.inbo.be) is used as website, while INBOmd uses [https://www.vlaanderen.be/inbo](https://www.vlaanderen.be/inbo), which is much longer and not catchy.  I suggest replacing it with the shorter [www.inbo.be](https://www.inbo.be), and maybe [www.inbo.be/en](https://www.inbo.be/en) for the English version?  In this case we could suggest to add '/en' in the English Word version as well?

**Comment by ThierryO** [comment]
We should verify this with the communication team first. So far they OK'ed the current version.

**Comment by ElsLommelen** [comment]
Apparently the official url is [www.vlaanderen.be/inbo](https://www.vlaanderen.be/inbo) and the Word templates use the old version, so we can just leave it as is.  So I'll close this issue and remove the PR.
