### ISSUE TITLE
url inbo website

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/INBOmd#83]
For the url of the inbo website, our spokesman has a preference for the short 'vlaanderen.be/inbo' instead of 'www.vlaanderen.be/inbo' (used in slideshows) or 'https://www.vlaanderen.be/inbo' (used in reports).  Maybe something to be changed in a next version of INBOmd?  (It seems a bit overkill to make a new INBOmd version for this minor change.)

**Comment by ThierryO** [comment]
fixed in #84
